stages:
  - deploy-dev
  - deploy-prod

deploy-dev:
  stage: deploy-dev
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DEV_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo 'StrictHostKeyChecking=accept-new' > ~/.ssh/config

  script:
    - rsync -avz --delete docs/_build/ $DEV_SSH_HOST:caddy/socketdocs
    - ssh $DEV_SSH_HOST "bash deploy.sh newsocket"

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-prod:
  stage: deploy-prod
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$PROD_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo 'StrictHostKeyChecking=accept-new' > ~/.ssh/config

  script:
    - ssh $PROD_SSH_HOST "bash deploy.sh newsocket"

  rules:
    - if: $CI_COMMIT_TAG
