networks:
    fliji-db:
      name: fliji-db
      external: true

services:
  fliji-sockets:
    container_name: fliji-sockets
    image: harbor.fliji.xyz/fliji/sockets:main
    env_file: .env
    entrypoint: ./entrypoint-sockets.sh
    networks:
        - fliji-db
    # environment:
    #   TZ: Europe/Moscow

  fliji-sockets-api:
    container_name: fliji-sockets-api
    image: harbor.fliji.xyz/fliji/sockets:main
    entrypoint: ./entrypoint.sh
    env_file: .env
    networks:
        - fliji-db
    # environment:
    #   TZ: Europe/Moscow
