networks:
    fliji-db:
      name: fliji-db
      external: true

services:
  fliji-sockets:
    container_name: fliji-sockets
    image: fliji_sockets_local_image:latest
    env_file: .env
    entrypoint: ./entrypoint.sh
    ports:
      - "8097:80"
    networks:
        - fliji-db