networks:
    fliji-db:
      name: fliji-db
      external: true

services:
  fliji-sockets:
    container_name: fliji-sockets
    image: ${FLIJI_SOCKETS_IMAGE:-harbor.fliji.xyz/fliji/sockets:main}
    env_file: .env
    entrypoint: ./entrypoint-sockets.sh
    networks:
        - fliji-db

  fliji-sockets-api:
    container_name: fliji-sockets-api
    image: ${FLIJI_SOCKETS_IMAGE:-harbor.fliji.xyz/fliji/sockets:main}
    entrypoint: ./entrypoint.sh
    env_file: .env
    networks:
        - fliji-db

  fliji-sockets-event-listener:
    container_name: fliji-sockets-event-listener
    image: ${FLIJI_SOCKETS_IMAGE:-harbor.fliji.xyz/fliji/sockets:main}
    entrypoint: ./entrypoint-event-listener.sh
    env_file: .env
    networks:
        - fliji-db