[tool.pdm]
distribution = false
[tool.pdm.scripts]
_.env_file = ".env"
socketio = 'uvicorn fliji_sockets.sio_main:sio_asgi_app --host 0.0.0.0 --port 8097 --reload'
socketio-prod = 'uvicorn fliji_sockets.sio_main:sio_asgi_app --proxy-headers --host 0.0.0.0 --port 80'
event-listener = {call = "fliji_sockets.api_event_listener:main"}
docs = "sphinx-build -b html docs/source docs/_build"

[tool.pdm.dev-dependencies]
dev = [
    "sphinx>=7.2.6",
    "autodoc-pydantic>=2.1.0",
]
[project]
name = "fliji-sockets"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    { name = "", email = "none" },
]
dependencies = [
    "python-socketio==4.6.1",
    "uvicorn[standard]>=0.27.1",
    "pymongo>=4.6.1",
    "httpx>=0.26.0",
    "nats-py>=2.7.2",
    "aioredis==1.3.1",
    "sentry-sdk>=2.4.0",
    "pydantic>=2.7.3",
]
requires-python = "==3.10.*"
readme = "README.md"
license = { text = "Proprietary" }


